<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE products [
    <!ELEMENT products (product)>
    <!ELEMENT product (name, description, price)>

    
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT price (#PCDATA)>


]>


<products>
    <product>
        <name> Levi  </name>
        <description> Resin </description>
        <price> PHP 15000 </price>
    </product>
</products>